### ISSUE TITLE
Iteration-based approach is slow for late-time slices

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/pydap.handlers.hdf5#3]
The code for this handler tries to be very generic. It *has* to be very generic, because it's handling HDF5 files of many, many different types, shapes and sizes.

One thing that it does very poorly, and a major mistake that was made when originally writing this code, was that it uses [`itertools.islice`](https://docs.python.org/2/library/itertools.html#itertools.islice) to [generically apply](https://github.com/pacificclimate/pydap.handlers.hdf5/blob/master/src/pydap/handlers/hdf5/__init__.py#L147) a multidimensional slice object to a multidimensional data cube.

On one hand, this is very elegant, in that it can handle a wide range of cases. But on the other, it's ineffectively un-performant, particularly for slices that start toward the end of the iterator. The implementation of `islice` (I *assume*) is that it iterates through its input stream until it gets to value of the beginning of the slice. This is fine for small length iterators or cheap to generate iterators. But when the generator is coming from a very expensive disk read, it could take minutes or hours to get to the correct spot.

We don't *need* to do this, because the HDF5 interface gives us random access to the file. We need to rewrite this code so that the slicing stacks up, but eventually translates into a direct slice operation on the HDF5 file, and *then* begins iterating from there.

**Comment by rod-glover** [comment]
A possibly not very useful couple of thoughts: 

- `netcdf4` provides a `numpy`-like interface to the data that simplifies slicing. Two big questions: performance and feasibility of transitioning this code to netcdf4

- Just possibly the [chunking code in `nchelpers`](https://github.com/pacificclimate/nchelpers/blob/master/nchelpers/iteration.py) code could be useful here. It's based on `netcdf4` slicing and is used to [compute the variable value range](https://github.com/pacificclimate/nchelpers/blob/master/nchelpers/__init__.py#L1016), but could easily be adapted to other purposes.

**Comment by jameshiebert** [comment]
Yeah, `h5py` has the same `numpy`-like interface for slicing. Lack of a software interface to NetCDF4/HDF5 data is not the problem.

The problem is more the fact that this code has to provide an iteration interface (because, you know, 150GB files) and it's trying to provide one single iteration interface to a very complex and varied set of base datatypes (OPeNDAP has four types: array, structure, sequence, grid). and doesn't do a particularly good job of doing so in a clear way.

I'm reasonably confident that we can fix this without needing to change out `h5py` for `netcdf4-python`. But your chunking code in `nchelpers` does look like a useful approach. Thanks for noting that.

**Comment by jameshiebert** [comment]
In the mean time, until we have fixed this, we should highly recommend that users simply download from the beginning of the timeseries `t=0`. It's definitely non-ideal, but at least they'll get the data without a timeout.

**Comment by jameshiebert** [comment]
Viable patch underway. Stand by for further testing.
